# Generated by Django 6.0.3 on 2026-03-17 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Nubank, Itaú Black', max_length=50)),
                ('limite_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_fechamento', models.IntegerField(help_text='Dia em que a fatura vira')),
                ('dia_vencimento', models.IntegerField(help_text='Dia de pagar o boleto')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo_regra', models.CharField(choices=[('ESSENCIAL', 'Necessidade (50%)'), ('ESTILO_VIDA', 'Desejo/Emoção (30%)'), ('FUTURO', 'Investimento/Reserva (20%)')], max_length=20)),
                ('orcamento_sugerido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_owner', models.BooleanField(default=False, help_text='Marque True apenas para o seu perfil. False para os amigos.')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Nome que vem na fatura', max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_compra', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente (Na fatura aberta)'), ('FATURADO', 'Faturado (Fatura fechada)'), ('PAGO', 'Pago/Quitado')], default='PENDENTE', max_length=15)),
                ('parcela_atual', models.IntegerField(default=1)),
                ('total_parcelas', models.IntegerField(default=1)),
                ('cartao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='core.cartaocredito')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='core.categoria')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='core.pessoa')),
            ],
        ),
    ]
