# Generated by Django 6.0.3 on 2026-03-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='ano_fatura',
            field=models.IntegerField(default=2026, help_text='Ano de competência da fatura'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='mes_fatura',
            field=models.IntegerField(default=1, help_text='Mês de competência da fatura'),
        ),
    ]
