# Generated by Django 6.0.3 on 2026-03-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transacao_ano_fatura_transacao_mes_fatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='renda_mensal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Usado para calcular a regra 50/30/20 (Apenas para o Titular)', max_digits=10),
        ),
    ]
