# Generated by Django 6.0.3 on 2026-03-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_pessoa_renda_mensal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
