# Generated by Django 6.0.3 on 2026-03-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pessoa_chave_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
