# Generated by Django 6.0.3 on 2026-03-19 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pessoa_is_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cofre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('meta_valor', models.DecimalField(decimal_places=2, help_text='O valor total (Boss) que você quer atingir', max_digits=10)),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0.0, help_text='Ouro guardado até o momento', max_digits=10)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instituicao')),
            ],
        ),
    ]
